[package]
name = "asteroids-wasm"
version = "0.1.0"
authors = ["Alex Yip"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quicksilver = "0.4.0-alpha0.5"
rand = "0.7.3"